-- MySQL Script generated by MySQL Workbench
-- Fri May  9 10:29:53 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NOT NULL,
  `activo` INT NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `tipoUsuario` ENUM("EMPRESA", "CLIENTE","ADMIN") NULL,
  `dni` VARCHAR(45) NULL,
  `razonsocial` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `RUC` VARCHAR(45) NULL,
  `token_reset` VARCHAR(45) NULL,
  `fecha_expiracion_token` DATE NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descuento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Descuento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Descuento` (
  `idDescuento` INT NOT NULL AUTO_INCREMENT COMMENT '0: descuento nulo\n1: descuento 0.10',
  `numDescuento` INT NOT NULL COMMENT 'Porcentaje:\n\n10\n20',
  `activo` INT NULL,
  PRIMARY KEY (`idDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `idDescuento` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  INDEX `fk_Categoria_Descuento1_idx` (`idDescuento` ASC) ,
  CONSTRAINT `fk_Categoria_Descuento1`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `mydb`.`Descuento` (`idDescuento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Producto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `stock` INT NOT NULL,
  `precio` DOUBLE NOT NULL,
  `Imagen` LONGBLOB NULL,
  `activo` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria1_idx` (`idCategoria` ASC) ,
  CONSTRAINT `fk_Producto_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`OrdenVenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`OrdenVenta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`OrdenVenta` (
  `idOrdenVenta` INT NOT NULL AUTO_INCREMENT,
  `estado_compra` ENUM('pendiente', 'pagado', 'enviado', 'entregado') NOT NULL,
  `fecha_orden` DATE NOT NULL,
  `activo` INT NULL,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idOrdenVenta`),
  INDEX `fk_OrdenVenta_Usuario1_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_OrdenVenta_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Detalle` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Detalle` (
  `id_orden` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `precio_unitario` DOUBLE NOT NULL,
  INDEX `FK_orden_item_idx` (`id_orden` ASC) ,
  INDEX `FK_producto_item_idx` (`id_producto` ASC) ,
  PRIMARY KEY (`id_orden`, `id_producto`),
  CONSTRAINT `FK_orden_item`
    FOREIGN KEY (`id_orden`)
    REFERENCES `mydb`.`OrdenVenta` (`idOrdenVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_producto_item`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ComprobantePago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ComprobantePago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ComprobantePago` (
  `idComprobantePago` INT NOT NULL AUTO_INCREMENT,
  `id_orden` INT NOT NULL,
  `metodo_pago` ENUM('efectivo', 'tarjeta') NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `monto_total` DOUBLE NOT NULL,
  PRIMARY KEY (`idComprobantePago`),
  INDEX `FK_orden_Comprobante_idx` (`id_orden` ASC) ,
  UNIQUE INDEX `id_orden_UNIQUE` (`id_orden` ASC) ,
  CONSTRAINT `FK_orden_Comprobante`
    FOREIGN KEY (`id_orden`)
    REFERENCES `mydb`.`OrdenVenta` (`idOrdenVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Entrega` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Entrega` (
  `idEntrega` INT NOT NULL AUTO_INCREMENT,
  `id_orden` INT NOT NULL,
  `fecha_entrega` DATETIME NOT NULL,
  `direccion` VARCHAR(120) NULL,
  `dni` INT NULL,
  `TipoEntrega` ENUM('DELIVERY', 'RECOJO') NOT NULL,
  PRIMARY KEY (`idEntrega`),
  INDEX `FK_ordenVenta_TipoEntrega_idx` (`id_orden` ASC) ,
  UNIQUE INDEX `id_orden_UNIQUE` (`id_orden` ASC) ,
  CONSTRAINT `FK_ordenVenta_TipoEntrega`
    FOREIGN KEY (`id_orden`)
    REFERENCES `mydb`.`OrdenVenta` (`idOrdenVenta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Boleta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Boleta` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Boleta` (
  `idBoleta` INT NOT NULL,
  `dni` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  PRIMARY KEY (`idBoleta`),
  UNIQUE INDEX `idComprobante_UNIQUE` (`idBoleta` ASC) ,
  CONSTRAINT `fk_Comprobante_Boleta`
    FOREIGN KEY (`idBoleta`)
    REFERENCES `mydb`.`ComprobantePago` (`idComprobantePago`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `idFactura` INT NOT NULL,
  `RUC` VARCHAR(11) NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `direccion_fiscal` VARCHAR(150) NOT NULL,
  `fecha_emision` DATETIME NOT NULL,
  PRIMARY KEY (`idFactura`),
  UNIQUE INDEX `idComprobante_UNIQUE` (`idFactura` ASC) ,
  CONSTRAINT `fk_comprobante_factura`
    FOREIGN KEY (`idFactura`)
    REFERENCES `mydb`.`ComprobantePago` (`idComprobantePago`)
    ON DELETE cascade
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cotizacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cotizacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cotizacion` (
  `idCotizacion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `estadoCotizacion` VARCHAR(45) NOT NULL COMMENT 'estado de la cotización:\nEn proceso\nRevisado',
  PRIMARY KEY (`idCotizacion`),
  INDEX `fk_Cotización_Usuario1_idx` (`idUsuario` ASC) ,
  CONSTRAINT `fk_Cotización_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productoCotizado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`productoCotizado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`productoCotizado` (
  `idproductoCotizado` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `cantidad` INT NOT NULL,
  `precioCotizado` DOUBLE NULL,
  `idCotizacion` INT NOT NULL,
  PRIMARY KEY (`idproductoCotizado`),
  INDEX `fk_productoCotizado_Cotizacion1_idx` (`idCotizacion` ASC) ,
  CONSTRAINT `fk_productoCotizado_Cotizacion1`
    FOREIGN KEY (`idCotizacion`)
    REFERENCES `mydb`.`Cotizacion` (`idCotizacion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Notificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Notificacion` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Notificacion` (
  `idNotificacion` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `mensaje` VARCHAR(45) NOT NULL,
  `fecha_envio` DATETIME NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `asunto` varchar(45) NULL,
  PRIMARY KEY (`idNotificacion`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
